/**
 * Approximate residential electricity tariffs and feed-in rates, plus
 * typical annual household consumption, by country. ~100 countries supported.
 *
 * Tariffs are residential / domestic averages in **local currency per kWh**,
 * gathered from public sources (Eurostat 2024-25 H1, IEA, GlobalPetrolPrices,
 * Ember, World Bank, national utility tariffs). They are intentional
 * approximations — markets with regulated, subsidised, or volatile prices
 * (AR, LB, VE, IR, etc.) carry larger uncertainty. The wizard surfaces a
 * "data as of" stamp so users can verify and override.
 *
 * Currency:
 *  - "symbol" is what we render in inputs (€, $, ₹, etc.) — trailing space
 *    where the symbol is multi-character (e.g. "C$ 1,234").
 *  - "currencyCode" is ISO-4217 (used downstream for accounting / payments).
 *  - All prices are stored in the local currency per kWh; no FX conversion.
 */

export interface CountryDefaults {
  countryCode: string;
  countryName: string;
  currencyCode: string;
  symbol: string;
  importPricePerKwh: number;
  exportPricePerKwh: number;
  dayPricePerKwh: number;
  nightPricePerKwh: number;
  annualKwh: number;
  /** Upfront grant amount in local currency. 0 = no scheme modelled. */
  grant: number;
  /** Display label for the grant scheme, e.g. "SEAI grant", "Federal ITC". */
  grantSchemeName: string;
  /** Average optimal panel tilt for residential roofs (degrees). */
  typicalTiltDeg: number;
  /** Examples of common time-of-use tariff names in this market. */
  touTariffExamples: string;
}

export const TARIFF_DATA_AS_OF = '2026-05';

const GENERIC_TOU = 'time-of-use / off-peak rates';
const GENERIC_GRANT = 'Local incentives may apply';

// Lookup keyed by ISO-3166-1 alpha-2 lowercase (matches Nominatim's
// `country_code` field).
const COUNTRY_DEFAULTS: Record<string, CountryDefaults> = {
  // ── Western Europe (Eurozone + neighbours) ─────────────────────────
  ie: { countryCode: 'ie', countryName: 'Ireland',         currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.433, exportPricePerKwh: 0.21,  dayPricePerKwh: 0.433, nightPricePerKwh: 0.15,  annualKwh: 4200,  grant: 3000, grantSchemeName: 'SEAI grant',                    typicalTiltDeg: 35, touTariffExamples: 'Smart Meter, EcoTracker, Night Saver' },
  gb: { countryCode: 'gb', countryName: 'United Kingdom',  currencyCode: 'GBP', symbol: '£',     importPricePerKwh: 0.245, exportPricePerKwh: 0.15,  dayPricePerKwh: 0.245, nightPricePerKwh: 0.10,  annualKwh: 3100,  grant: 0,    grantSchemeName: 'Smart Export Guarantee',        typicalTiltDeg: 35, touTariffExamples: 'Octopus Agile, Economy 7, Cosy' },
  fr: { countryCode: 'fr', countryName: 'France',          currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.252, exportPricePerKwh: 0.13,  dayPricePerKwh: 0.252, nightPricePerKwh: 0.18,  annualKwh: 4500,  grant: 0,    grantSchemeName: "MaPrimeRénov' / EDF OA",        typicalTiltDeg: 35, touTariffExamples: 'Heures Creuses, Tempo' },
  de: { countryCode: 'de', countryName: 'Germany',         currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.402, exportPricePerKwh: 0.082, dayPricePerKwh: 0.402, nightPricePerKwh: 0.25,  annualKwh: 3500,  grant: 0,    grantSchemeName: 'KfW 270 / EEG Einspeisevergütung', typicalTiltDeg: 32, touTariffExamples: 'HT/NT, Tibber dynamisch' },
  es: { countryCode: 'es', countryName: 'Spain',           currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.234, exportPricePerKwh: 0.09,  dayPricePerKwh: 0.234, nightPricePerKwh: 0.10,  annualKwh: 3300,  grant: 0,    grantSchemeName: 'PNIEC / IRPF deduction',        typicalTiltDeg: 30, touTariffExamples: 'Tarifa 2.0TD, PVPC' },
  it: { countryCode: 'it', countryName: 'Italy',           currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.378, exportPricePerKwh: 0.10,  dayPricePerKwh: 0.378, nightPricePerKwh: 0.22,  annualKwh: 2700,  grant: 0,    grantSchemeName: 'Detrazione 50% / Superbonus',   typicalTiltDeg: 30, touTariffExamples: 'F1/F2/F3 fasce orarie' },
  nl: { countryCode: 'nl', countryName: 'Netherlands',     currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.40,  exportPricePerKwh: 0.08,  dayPricePerKwh: 0.40,  nightPricePerKwh: 0.30,  annualKwh: 2900,  grant: 0,    grantSchemeName: 'BTW-teruggave / SDE++',         typicalTiltDeg: 35, touTariffExamples: 'Dynamische tarieven, dag/nacht' },
  be: { countryCode: 'be', countryName: 'Belgium',         currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.418, exportPricePerKwh: 0.075, dayPricePerKwh: 0.418, nightPricePerKwh: 0.28,  annualKwh: 3500,  grant: 0,    grantSchemeName: 'Mijn VerbouwPremie / Prime',    typicalTiltDeg: 35, touTariffExamples: 'Tweevoudig dag/nacht' },
  pt: { countryCode: 'pt', countryName: 'Portugal',        currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.225, exportPricePerKwh: 0.08,  dayPricePerKwh: 0.225, nightPricePerKwh: 0.13,  annualKwh: 3200,  grant: 0,    grantSchemeName: 'Fundo Ambiental',               typicalTiltDeg: 30, touTariffExamples: 'Bi-horária, tri-horária' },
  at: { countryCode: 'at', countryName: 'Austria',         currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.345, exportPricePerKwh: 0.10,  dayPricePerKwh: 0.345, nightPricePerKwh: 0.20,  annualKwh: 3700,  grant: 0,    grantSchemeName: 'OeMAG / Klima- und Energiefonds', typicalTiltDeg: 35, touTariffExamples: 'Smart Meter dynamisch' },
  ch: { countryCode: 'ch', countryName: 'Switzerland',     currencyCode: 'CHF', symbol: 'CHF ',  importPricePerKwh: 0.32,  exportPricePerKwh: 0.10,  dayPricePerKwh: 0.32,  nightPricePerKwh: 0.20,  annualKwh: 4500,  grant: 0,    grantSchemeName: 'Pronovo Einmalvergütung',       typicalTiltDeg: 35, touTariffExamples: 'Hoch-/Niedertarif' },
  lu: { countryCode: 'lu', countryName: 'Luxembourg',      currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.30,  exportPricePerKwh: 0.085, dayPricePerKwh: 0.30,  nightPricePerKwh: 0.18,  annualKwh: 3800,  grant: 0,    grantSchemeName: 'PRIMe House / Klimabonus',      typicalTiltDeg: 35, touTariffExamples: 'Bi-horaire' },
  gr: { countryCode: 'gr', countryName: 'Greece',          currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.18,  exportPricePerKwh: 0.07,  dayPricePerKwh: 0.18,  nightPricePerKwh: 0.10,  annualKwh: 3900,  grant: 0,    grantSchemeName: 'Photovoltaics on Roofs',        typicalTiltDeg: 30, touTariffExamples: 'Νυχτερινό τιμολόγιο' },
  mt: { countryCode: 'mt', countryName: 'Malta',           currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.13,  exportPricePerKwh: 0.155, dayPricePerKwh: 0.13,  nightPricePerKwh: 0.10,  annualKwh: 3800,  grant: 0,    grantSchemeName: 'PV grant scheme',               typicalTiltDeg: 25, touTariffExamples: 'Residential bi-rate' },
  cy: { countryCode: 'cy', countryName: 'Cyprus',          currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.21,  exportPricePerKwh: 0.10,  dayPricePerKwh: 0.21,  nightPricePerKwh: 0.13,  annualKwh: 4500,  grant: 0,    grantSchemeName: 'PV self-consumption scheme',    typicalTiltDeg: 30, touTariffExamples: 'Bi-rate, off-peak' },
  is: { countryCode: 'is', countryName: 'Iceland',         currencyCode: 'ISK', symbol: 'kr ',   importPricePerKwh: 18,    exportPricePerKwh: 8,     dayPricePerKwh: 18,    nightPricePerKwh: 14,    annualKwh: 4500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 50, touTariffExamples: GENERIC_TOU },

  // ── Eastern / Central Europe ──────────────────────────────────────
  pl: { countryCode: 'pl', countryName: 'Poland',          currencyCode: 'PLN', symbol: 'zł ',   importPricePerKwh: 0.85,  exportPricePerKwh: 0.30,  dayPricePerKwh: 0.85,  nightPricePerKwh: 0.45,  annualKwh: 2400,  grant: 0,    grantSchemeName: 'Mój Prąd',                      typicalTiltDeg: 35, touTariffExamples: 'G12, G12w' },
  cz: { countryCode: 'cz', countryName: 'Czech Republic',  currencyCode: 'CZK', symbol: 'Kč ',   importPricePerKwh: 6.50,  exportPricePerKwh: 1.50,  dayPricePerKwh: 6.50,  nightPricePerKwh: 3.50,  annualKwh: 2500,  grant: 0,    grantSchemeName: 'Nová zelená úsporám',           typicalTiltDeg: 35, touTariffExamples: 'D25d, D26d' },
  hu: { countryCode: 'hu', countryName: 'Hungary',         currencyCode: 'HUF', symbol: 'Ft ',   importPricePerKwh: 36,    exportPricePerKwh: 22,    dayPricePerKwh: 36,    nightPricePerKwh: 22,    annualKwh: 2700,  grant: 0,    grantSchemeName: 'Lakossági Napelem Pályázat',    typicalTiltDeg: 35, touTariffExamples: 'A1, A2, vezérelt' },
  ro: { countryCode: 'ro', countryName: 'Romania',         currencyCode: 'RON', symbol: 'lei ',  importPricePerKwh: 1.30,  exportPricePerKwh: 0.27,  dayPricePerKwh: 1.30,  nightPricePerKwh: 0.85,  annualKwh: 2200,  grant: 0,    grantSchemeName: 'Casa Verde Fotovoltaice',       typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },
  bg: { countryCode: 'bg', countryName: 'Bulgaria',        currencyCode: 'BGN', symbol: 'лв ',   importPricePerKwh: 0.25,  exportPricePerKwh: 0.10,  dayPricePerKwh: 0.25,  nightPricePerKwh: 0.13,  annualKwh: 3500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 35, touTariffExamples: 'дневна/нощна' },
  hr: { countryCode: 'hr', countryName: 'Croatia',         currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.15,  exportPricePerKwh: 0.05,  dayPricePerKwh: 0.15,  nightPricePerKwh: 0.085, annualKwh: 3000,  grant: 0,    grantSchemeName: 'Fond za zaštitu okoliša',       typicalTiltDeg: 35, touTariffExamples: 'jednotarifna/dvotarifna' },
  si: { countryCode: 'si', countryName: 'Slovenia',        currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.18,  exportPricePerKwh: 0.06,  dayPricePerKwh: 0.18,  nightPricePerKwh: 0.10,  annualKwh: 3500,  grant: 0,    grantSchemeName: 'Eko sklad',                     typicalTiltDeg: 35, touTariffExamples: 'višja/nižja tarifa' },
  sk: { countryCode: 'sk', countryName: 'Slovakia',        currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.22,  exportPricePerKwh: 0.06,  dayPricePerKwh: 0.22,  nightPricePerKwh: 0.13,  annualKwh: 2800,  grant: 0,    grantSchemeName: 'Zelená domácnostiam',           typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },
  ee: { countryCode: 'ee', countryName: 'Estonia',         currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.18,  exportPricePerKwh: 0.07,  dayPricePerKwh: 0.18,  nightPricePerKwh: 0.10,  annualKwh: 4500,  grant: 0,    grantSchemeName: 'KredEx PV toetus',              typicalTiltDeg: 45, touTariffExamples: 'päev/öö' },
  lv: { countryCode: 'lv', countryName: 'Latvia',          currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.20,  exportPricePerKwh: 0.07,  dayPricePerKwh: 0.20,  nightPricePerKwh: 0.11,  annualKwh: 3000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 45, touTariffExamples: GENERIC_TOU },
  lt: { countryCode: 'lt', countryName: 'Lithuania',       currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.19,  exportPricePerKwh: 0.07,  dayPricePerKwh: 0.19,  nightPricePerKwh: 0.10,  annualKwh: 2800,  grant: 0,    grantSchemeName: 'APVA parama',                   typicalTiltDeg: 40, touTariffExamples: 'dieninis/naktinis' },
  ua: { countryCode: 'ua', countryName: 'Ukraine',         currencyCode: 'UAH', symbol: '₴ ',    importPricePerKwh: 4.32,  exportPricePerKwh: 4.20,  dayPricePerKwh: 4.32,  nightPricePerKwh: 2.16,  annualKwh: 3000,  grant: 0,    grantSchemeName: 'Зелений тариф',                 typicalTiltDeg: 35, touTariffExamples: 'тризонний' },
  tr: { countryCode: 'tr', countryName: 'Turkey',          currencyCode: 'TRY', symbol: '₺ ',    importPricePerKwh: 2.50,  exportPricePerKwh: 1.80,  dayPricePerKwh: 2.50,  nightPricePerKwh: 1.30,  annualKwh: 2500,  grant: 0,    grantSchemeName: 'YEKDEM',                         typicalTiltDeg: 30, touTariffExamples: '3 zamanlı tarife' },
  rs: { countryCode: 'rs', countryName: 'Serbia',          currencyCode: 'RSD', symbol: 'дин ',  importPricePerKwh: 11,    exportPricePerKwh: 6,     dayPricePerKwh: 11,    nightPricePerKwh: 6,     annualKwh: 3500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },
  ru: { countryCode: 'ru', countryName: 'Russia',          currencyCode: 'RUB', symbol: '₽ ',    importPricePerKwh: 5.80,  exportPricePerKwh: 3.50,  dayPricePerKwh: 5.80,  nightPricePerKwh: 2.90,  annualKwh: 4200,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 45, touTariffExamples: 'двухтарифный' },
  md: { countryCode: 'md', countryName: 'Moldova',         currencyCode: 'MDL', symbol: 'L ',    importPricePerKwh: 2.86,  exportPricePerKwh: 1.40,  dayPricePerKwh: 2.86,  nightPricePerKwh: 1.60,  annualKwh: 2200,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },
  by: { countryCode: 'by', countryName: 'Belarus',         currencyCode: 'BYN', symbol: 'Br ',   importPricePerKwh: 0.25,  exportPricePerKwh: 0.10,  dayPricePerKwh: 0.25,  nightPricePerKwh: 0.13,  annualKwh: 3000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 45, touTariffExamples: GENERIC_TOU },
  ge: { countryCode: 'ge', countryName: 'Georgia',         currencyCode: 'GEL', symbol: '₾ ',    importPricePerKwh: 0.18,  exportPricePerKwh: 0.10,  dayPricePerKwh: 0.18,  nightPricePerKwh: 0.10,  annualKwh: 2500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },
  am: { countryCode: 'am', countryName: 'Armenia',         currencyCode: 'AMD', symbol: '֏ ',    importPricePerKwh: 50,    exportPricePerKwh: 28,    dayPricePerKwh: 50,    nightPricePerKwh: 35,    annualKwh: 2200,  grant: 0,    grantSchemeName: 'PSRC Net Metering',             typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },
  az: { countryCode: 'az', countryName: 'Azerbaijan',      currencyCode: 'AZN', symbol: '₼ ',    importPricePerKwh: 0.07,  exportPricePerKwh: 0.05,  dayPricePerKwh: 0.07,  nightPricePerKwh: 0.05,  annualKwh: 2400,  grant: 0,    grantSchemeName: 'SOCAR Renewable Programme',     typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },

  // ── Balkans (developed-country completeness) ──────────────────────
  al: { countryCode: 'al', countryName: 'Albania',         currencyCode: 'ALL', symbol: 'L ',    importPricePerKwh: 11,    exportPricePerKwh: 6,     dayPricePerKwh: 11,    nightPricePerKwh: 7,     annualKwh: 3500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },
  ba: { countryCode: 'ba', countryName: 'Bosnia & Herzegovina', currencyCode: 'BAM', symbol: 'KM ', importPricePerKwh: 0.18, exportPricePerKwh: 0.07, dayPricePerKwh: 0.18, nightPricePerKwh: 0.10, annualKwh: 3500, grant: 0, grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },
  mk: { countryCode: 'mk', countryName: 'North Macedonia', currencyCode: 'MKD', symbol: 'ден ',  importPricePerKwh: 6.20,  exportPricePerKwh: 3.20,  dayPricePerKwh: 6.20,  nightPricePerKwh: 3.20,  annualKwh: 3300,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },
  me: { countryCode: 'me', countryName: 'Montenegro',      currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.10,  exportPricePerKwh: 0.05,  dayPricePerKwh: 0.10,  nightPricePerKwh: 0.05,  annualKwh: 3700,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },
  xk: { countryCode: 'xk', countryName: 'Kosovo',          currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.07,  exportPricePerKwh: 0.04,  dayPricePerKwh: 0.07,  nightPricePerKwh: 0.04,  annualKwh: 3500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },

  // ── Microstates / small developed economies ───────────────────────
  li: { countryCode: 'li', countryName: 'Liechtenstein',   currencyCode: 'CHF', symbol: 'CHF ',  importPricePerKwh: 0.30,  exportPricePerKwh: 0.10,  dayPricePerKwh: 0.30,  nightPricePerKwh: 0.18,  annualKwh: 4500,  grant: 0,    grantSchemeName: 'EMG förderung',                 typicalTiltDeg: 35, touTariffExamples: 'Hoch-/Niedertarif' },
  mc: { countryCode: 'mc', countryName: 'Monaco',          currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.20,  exportPricePerKwh: 0.10,  dayPricePerKwh: 0.20,  nightPricePerKwh: 0.13,  annualKwh: 3500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 30, touTariffExamples: GENERIC_TOU },
  ad: { countryCode: 'ad', countryName: 'Andorra',         currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.13,  exportPricePerKwh: 0.07,  dayPricePerKwh: 0.13,  nightPricePerKwh: 0.08,  annualKwh: 3500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },
  sm: { countryCode: 'sm', countryName: 'San Marino',      currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.30,  exportPricePerKwh: 0.10,  dayPricePerKwh: 0.30,  nightPricePerKwh: 0.18,  annualKwh: 3000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },
  mo: { countryCode: 'mo', countryName: 'Macao',           currencyCode: 'MOP', symbol: 'MOP$ ', importPricePerKwh: 1.30,  exportPricePerKwh: 0.80,  dayPricePerKwh: 1.30,  nightPricePerKwh: 1.00,  annualKwh: 5000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 22, touTariffExamples: GENERIC_TOU },
  bn: { countryCode: 'bn', countryName: 'Brunei',          currencyCode: 'BND', symbol: 'B$ ',   importPricePerKwh: 0.10,  exportPricePerKwh: 0.05,  dayPricePerKwh: 0.10,  nightPricePerKwh: 0.07,  annualKwh: 8000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 5,  touTariffExamples: GENERIC_TOU },
  fi: { countryCode: 'fi', countryName: 'Finland',         currencyCode: 'EUR', symbol: '€',     importPricePerKwh: 0.21,  exportPricePerKwh: 0.06,  dayPricePerKwh: 0.21,  nightPricePerKwh: 0.10,  annualKwh: 7500,  grant: 0,    grantSchemeName: 'Energiavero-palautus',          typicalTiltDeg: 45, touTariffExamples: 'Pörssisähkö, yösähkö' },
  dk: { countryCode: 'dk', countryName: 'Denmark',         currencyCode: 'DKK', symbol: 'kr ',   importPricePerKwh: 2.85,  exportPricePerKwh: 0.50,  dayPricePerKwh: 2.85,  nightPricePerKwh: 2.00,  annualKwh: 4000,  grant: 0,    grantSchemeName: 'Skattefradrag PSO',             typicalTiltDeg: 40, touTariffExamples: 'Spotpris, dag/nat' },
  no: { countryCode: 'no', countryName: 'Norway',          currencyCode: 'NOK', symbol: 'kr ',   importPricePerKwh: 1.40,  exportPricePerKwh: 0.80,  dayPricePerKwh: 1.40,  nightPricePerKwh: 0.80,  annualKwh: 16000, grant: 0,    grantSchemeName: 'Enova-tilskudd',                typicalTiltDeg: 45, touTariffExamples: 'Spotpris, effekttariff' },
  se: { countryCode: 'se', countryName: 'Sweden',          currencyCode: 'SEK', symbol: 'kr ',   importPricePerKwh: 1.60,  exportPricePerKwh: 0.60,  dayPricePerKwh: 1.60,  nightPricePerKwh: 0.80,  annualKwh: 6000,  grant: 0,    grantSchemeName: 'Grön teknik (skatteavdrag)',    typicalTiltDeg: 45, touTariffExamples: 'Timpris, hög-/låglast' },

  // ── North America ─────────────────────────────────────────────────
  us: { countryCode: 'us', countryName: 'United States',   currencyCode: 'USD', symbol: '$',     importPricePerKwh: 0.165, exportPricePerKwh: 0.08,  dayPricePerKwh: 0.165, nightPricePerKwh: 0.10,  annualKwh: 10800, grant: 0,    grantSchemeName: 'Federal ITC (30%) + state credits', typicalTiltDeg: 30, touTariffExamples: 'TOU-D, NEM 3.0, EV-A' },
  ca: { countryCode: 'ca', countryName: 'Canada',          currencyCode: 'CAD', symbol: 'C$ ',   importPricePerKwh: 0.18,  exportPricePerKwh: 0.085, dayPricePerKwh: 0.18,  nightPricePerKwh: 0.10,  annualKwh: 11000, grant: 0,    grantSchemeName: 'Greener Homes / provincial',    typicalTiltDeg: 40, touTariffExamples: 'Time-of-Use, Tier 1/2' },
  mx: { countryCode: 'mx', countryName: 'Mexico',          currencyCode: 'MXN', symbol: 'MX$ ',  importPricePerKwh: 4.50,  exportPricePerKwh: 1.20,  dayPricePerKwh: 4.50,  nightPricePerKwh: 2.20,  annualKwh: 3000,  grant: 0,    grantSchemeName: 'Net metering (CFE)',            typicalTiltDeg: 25, touTariffExamples: 'DAC, Tarifa 1F' },

  // ── Central & South America ───────────────────────────────────────
  br: { countryCode: 'br', countryName: 'Brazil',          currencyCode: 'BRL', symbol: 'R$ ',   importPricePerKwh: 0.85,  exportPricePerKwh: 0.55,  dayPricePerKwh: 0.85,  nightPricePerKwh: 0.55,  annualKwh: 2200,  grant: 0,    grantSchemeName: 'SCEE compensation',             typicalTiltDeg: 25, touTariffExamples: 'Branca, convencional' },
  ar: { countryCode: 'ar', countryName: 'Argentina',       currencyCode: 'ARS', symbol: '$ ',    importPricePerKwh: 30,    exportPricePerKwh: 18,    dayPricePerKwh: 30,    nightPricePerKwh: 20,    annualKwh: 3300,  grant: 0,    grantSchemeName: 'Ley 27.424 Generación Distribuida', typicalTiltDeg: 30, touTariffExamples: GENERIC_TOU },
  cl: { countryCode: 'cl', countryName: 'Chile',           currencyCode: 'CLP', symbol: '$ ',    importPricePerKwh: 160,   exportPricePerKwh: 60,    dayPricePerKwh: 160,   nightPricePerKwh: 90,    annualKwh: 2800,  grant: 0,    grantSchemeName: 'Net billing (Ley 20.571)',     typicalTiltDeg: 30, touTariffExamples: 'BT-1, BT-3' },
  co: { countryCode: 'co', countryName: 'Colombia',        currencyCode: 'COP', symbol: 'COL$ ', importPricePerKwh: 800,   exportPricePerKwh: 500,   dayPricePerKwh: 800,   nightPricePerKwh: 500,   annualKwh: 2400,  grant: 0,    grantSchemeName: 'Ley 1715 / FENOGE',             typicalTiltDeg: 15, touTariffExamples: GENERIC_TOU },
  pe: { countryCode: 'pe', countryName: 'Peru',            currencyCode: 'PEN', symbol: 'S/ ',   importPricePerKwh: 0.70,  exportPricePerKwh: 0.30,  dayPricePerKwh: 0.70,  nightPricePerKwh: 0.45,  annualKwh: 1500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 20, touTariffExamples: GENERIC_TOU },
  uy: { countryCode: 'uy', countryName: 'Uruguay',         currencyCode: 'UYU', symbol: '$U ',   importPricePerKwh: 8.00,  exportPricePerKwh: 4.50,  dayPricePerKwh: 8.00,  nightPricePerKwh: 5.50,  annualKwh: 3000,  grant: 0,    grantSchemeName: 'UTE Microgeneración',           typicalTiltDeg: 30, touTariffExamples: GENERIC_TOU },
  ec: { countryCode: 'ec', countryName: 'Ecuador',         currencyCode: 'USD', symbol: '$',     importPricePerKwh: 0.10,  exportPricePerKwh: 0.05,  dayPricePerKwh: 0.10,  nightPricePerKwh: 0.07,  annualKwh: 1500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 15, touTariffExamples: GENERIC_TOU },
  py: { countryCode: 'py', countryName: 'Paraguay',        currencyCode: 'PYG', symbol: '₲ ',    importPricePerKwh: 350,   exportPricePerKwh: 200,   dayPricePerKwh: 350,   nightPricePerKwh: 250,   annualKwh: 2500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 25, touTariffExamples: GENERIC_TOU },
  bo: { countryCode: 'bo', countryName: 'Bolivia',         currencyCode: 'BOB', symbol: 'Bs ',   importPricePerKwh: 0.80,  exportPricePerKwh: 0.40,  dayPricePerKwh: 0.80,  nightPricePerKwh: 0.55,  annualKwh: 2000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 20, touTariffExamples: GENERIC_TOU },
  ve: { countryCode: 've', countryName: 'Venezuela',       currencyCode: 'VES', symbol: 'Bs ',   importPricePerKwh: 0.20,  exportPricePerKwh: 0.10,  dayPricePerKwh: 0.20,  nightPricePerKwh: 0.13,  annualKwh: 2500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 15, touTariffExamples: GENERIC_TOU },
  cr: { countryCode: 'cr', countryName: 'Costa Rica',      currencyCode: 'CRC', symbol: '₡ ',    importPricePerKwh: 100,   exportPricePerKwh: 50,    dayPricePerKwh: 100,   nightPricePerKwh: 60,    annualKwh: 2200,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 15, touTariffExamples: GENERIC_TOU },
  pa: { countryCode: 'pa', countryName: 'Panama',          currencyCode: 'USD', symbol: '$',     importPricePerKwh: 0.20,  exportPricePerKwh: 0.10,  dayPricePerKwh: 0.20,  nightPricePerKwh: 0.13,  annualKwh: 2400,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 15, touTariffExamples: GENERIC_TOU },
  do: { countryCode: 'do', countryName: 'Dominican Republic', currencyCode: 'DOP', symbol: 'RD$ ', importPricePerKwh: 9.50, exportPricePerKwh: 5.00, dayPricePerKwh: 9.50,  nightPricePerKwh: 6.50,  annualKwh: 2500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 18, touTariffExamples: GENERIC_TOU },
  gt: { countryCode: 'gt', countryName: 'Guatemala',       currencyCode: 'GTQ', symbol: 'Q ',    importPricePerKwh: 1.50,  exportPricePerKwh: 0.80,  dayPricePerKwh: 1.50,  nightPricePerKwh: 1.00,  annualKwh: 1800,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 15, touTariffExamples: GENERIC_TOU },
  jm: { countryCode: 'jm', countryName: 'Jamaica',         currencyCode: 'JMD', symbol: 'J$ ',   importPricePerKwh: 50,    exportPricePerKwh: 25,    dayPricePerKwh: 50,    nightPricePerKwh: 32,    annualKwh: 2000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 18, touTariffExamples: GENERIC_TOU },
  hn: { countryCode: 'hn', countryName: 'Honduras',        currencyCode: 'HNL', symbol: 'L ',    importPricePerKwh: 5.00,  exportPricePerKwh: 2.50,  dayPricePerKwh: 5.00,  nightPricePerKwh: 3.30,  annualKwh: 1500,  grant: 0,    grantSchemeName: 'Net metering (ENEE)',           typicalTiltDeg: 15, touTariffExamples: GENERIC_TOU },
  sv: { countryCode: 'sv', countryName: 'El Salvador',     currencyCode: 'USD', symbol: '$',     importPricePerKwh: 0.18,  exportPricePerKwh: 0.10,  dayPricePerKwh: 0.18,  nightPricePerKwh: 0.13,  annualKwh: 1700,  grant: 0,    grantSchemeName: 'CNE Net Metering',              typicalTiltDeg: 15, touTariffExamples: GENERIC_TOU },
  ni: { countryCode: 'ni', countryName: 'Nicaragua',       currencyCode: 'NIO', symbol: 'C$ ',   importPricePerKwh: 7.00,  exportPricePerKwh: 4.00,  dayPricePerKwh: 7.00,  nightPricePerKwh: 4.50,  annualKwh: 1500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 15, touTariffExamples: GENERIC_TOU },
  cu: { countryCode: 'cu', countryName: 'Cuba',            currencyCode: 'CUP', symbol: '$ ',    importPricePerKwh: 0.50,  exportPricePerKwh: 0.30,  dayPricePerKwh: 0.50,  nightPricePerKwh: 0.30,  annualKwh: 1500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 22, touTariffExamples: GENERIC_TOU },
  bs: { countryCode: 'bs', countryName: 'Bahamas',         currencyCode: 'BSD', symbol: 'B$ ',   importPricePerKwh: 0.30,  exportPricePerKwh: 0.20,  dayPricePerKwh: 0.30,  nightPricePerKwh: 0.20,  annualKwh: 4000,  grant: 0,    grantSchemeName: 'BPL Solar SSRG',                typicalTiltDeg: 24, touTariffExamples: GENERIC_TOU },
  bb: { countryCode: 'bb', countryName: 'Barbados',        currencyCode: 'BBD', symbol: 'Bds$ ', importPricePerKwh: 0.65,  exportPricePerKwh: 0.40,  dayPricePerKwh: 0.65,  nightPricePerKwh: 0.45,  annualKwh: 2500,  grant: 0,    grantSchemeName: 'BL&P Renewable Riders',         typicalTiltDeg: 13, touTariffExamples: GENERIC_TOU },
  tt: { countryCode: 'tt', countryName: 'Trinidad & Tobago', currencyCode: 'TTD', symbol: 'TT$ ', importPricePerKwh: 0.35, exportPricePerKwh: 0.20, dayPricePerKwh: 0.35,  nightPricePerKwh: 0.25,  annualKwh: 6000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 11, touTariffExamples: GENERIC_TOU },

  // ── Asia: East & Southeast ────────────────────────────────────────
  jp: { countryCode: 'jp', countryName: 'Japan',           currencyCode: 'JPY', symbol: '¥ ',    importPricePerKwh: 28,    exportPricePerKwh: 16,    dayPricePerKwh: 28,    nightPricePerKwh: 18,    annualKwh: 4500,  grant: 0,    grantSchemeName: 'FIT / FIP scheme',              typicalTiltDeg: 30, touTariffExamples: '時間帯別電灯' },
  kr: { countryCode: 'kr', countryName: 'South Korea',     currencyCode: 'KRW', symbol: '₩ ',    importPricePerKwh: 165,   exportPricePerKwh: 80,    dayPricePerKwh: 165,   nightPricePerKwh: 95,    annualKwh: 4500,  grant: 0,    grantSchemeName: 'KEPCO net metering',            typicalTiltDeg: 30, touTariffExamples: 'TOU residential' },
  cn: { countryCode: 'cn', countryName: 'China',           currencyCode: 'CNY', symbol: '¥ ',    importPricePerKwh: 0.55,  exportPricePerKwh: 0.20,  dayPricePerKwh: 0.55,  nightPricePerKwh: 0.30,  annualKwh: 1700,  grant: 0,    grantSchemeName: 'Local DRE subsidy',             typicalTiltDeg: 30, touTariffExamples: 'TOU 阶梯电价' },
  tw: { countryCode: 'tw', countryName: 'Taiwan',          currencyCode: 'TWD', symbol: 'NT$ ',  importPricePerKwh: 4.00,  exportPricePerKwh: 5.30,  dayPricePerKwh: 4.00,  nightPricePerKwh: 2.40,  annualKwh: 4500,  grant: 0,    grantSchemeName: 'Taipower FIT',                  typicalTiltDeg: 25, touTariffExamples: '時間電價' },
  hk: { countryCode: 'hk', countryName: 'Hong Kong',       currencyCode: 'HKD', symbol: 'HK$ ',  importPricePerKwh: 1.30,  exportPricePerKwh: 3.00,  dayPricePerKwh: 1.30,  nightPricePerKwh: 1.00,  annualKwh: 5500,  grant: 0,    grantSchemeName: 'Feed-in Tariff (CLP/HKE)',      typicalTiltDeg: 22, touTariffExamples: GENERIC_TOU },
  sg: { countryCode: 'sg', countryName: 'Singapore',       currencyCode: 'SGD', symbol: 'S$ ',   importPricePerKwh: 0.30,  exportPricePerKwh: 0.20,  dayPricePerKwh: 0.30,  nightPricePerKwh: 0.20,  annualKwh: 4200,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 10, touTariffExamples: GENERIC_TOU },
  my: { countryCode: 'my', countryName: 'Malaysia',        currencyCode: 'MYR', symbol: 'RM ',   importPricePerKwh: 0.50,  exportPricePerKwh: 0.31,  dayPricePerKwh: 0.50,  nightPricePerKwh: 0.30,  annualKwh: 4800,  grant: 0,    grantSchemeName: 'NEM 3.0 / SELCO',               typicalTiltDeg: 10, touTariffExamples: GENERIC_TOU },
  th: { countryCode: 'th', countryName: 'Thailand',        currencyCode: 'THB', symbol: '฿ ',    importPricePerKwh: 4.20,  exportPricePerKwh: 2.20,  dayPricePerKwh: 4.20,  nightPricePerKwh: 2.60,  annualKwh: 3500,  grant: 0,    grantSchemeName: 'PEA/MEA SPP',                   typicalTiltDeg: 15, touTariffExamples: 'TOU residential' },
  id: { countryCode: 'id', countryName: 'Indonesia',       currencyCode: 'IDR', symbol: 'Rp ',   importPricePerKwh: 1450,  exportPricePerKwh: 900,   dayPricePerKwh: 1450,  nightPricePerKwh: 1000,  annualKwh: 1500,  grant: 0,    grantSchemeName: 'PLN net metering',              typicalTiltDeg: 10, touTariffExamples: GENERIC_TOU },
  vn: { countryCode: 'vn', countryName: 'Vietnam',         currencyCode: 'VND', symbol: '₫ ',    importPricePerKwh: 2500,  exportPricePerKwh: 1900,  dayPricePerKwh: 2500,  nightPricePerKwh: 1700,  annualKwh: 1900,  grant: 0,    grantSchemeName: 'EVN net metering',              typicalTiltDeg: 15, touTariffExamples: GENERIC_TOU },
  ph: { countryCode: 'ph', countryName: 'Philippines',     currencyCode: 'PHP', symbol: '₱ ',    importPricePerKwh: 11,    exportPricePerKwh: 6,     dayPricePerKwh: 11,    nightPricePerKwh: 7,     annualKwh: 1800,  grant: 0,    grantSchemeName: 'Net metering (DOE)',            typicalTiltDeg: 15, touTariffExamples: GENERIC_TOU },
  mm: { countryCode: 'mm', countryName: 'Myanmar',         currencyCode: 'MMK', symbol: 'K ',    importPricePerKwh: 75,    exportPricePerKwh: 40,    dayPricePerKwh: 75,    nightPricePerKwh: 50,    annualKwh: 800,   grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 18, touTariffExamples: GENERIC_TOU },
  kh: { countryCode: 'kh', countryName: 'Cambodia',        currencyCode: 'KHR', symbol: '៛ ',    importPricePerKwh: 700,   exportPricePerKwh: 350,   dayPricePerKwh: 700,   nightPricePerKwh: 450,   annualKwh: 1500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 12, touTariffExamples: GENERIC_TOU },
  la: { countryCode: 'la', countryName: 'Laos',            currencyCode: 'LAK', symbol: '₭ ',    importPricePerKwh: 800,   exportPricePerKwh: 400,   dayPricePerKwh: 800,   nightPricePerKwh: 500,   annualKwh: 1200,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 18, touTariffExamples: GENERIC_TOU },

  // ── Asia: South ───────────────────────────────────────────────────
  in: { countryCode: 'in', countryName: 'India',           currencyCode: 'INR', symbol: '₹ ',    importPricePerKwh: 7.5,   exportPricePerKwh: 3.0,   dayPricePerKwh: 7.5,   nightPricePerKwh: 4.0,   annualKwh: 1800,  grant: 0,    grantSchemeName: 'PM Surya Ghar (subsidy)',       typicalTiltDeg: 25, touTariffExamples: 'TOD, slab tariff' },
  pk: { countryCode: 'pk', countryName: 'Pakistan',        currencyCode: 'PKR', symbol: '₨ ',    importPricePerKwh: 50,    exportPricePerKwh: 27,    dayPricePerKwh: 50,    nightPricePerKwh: 32,    annualKwh: 1500,  grant: 0,    grantSchemeName: 'AEDB Net Metering',             typicalTiltDeg: 30, touTariffExamples: GENERIC_TOU },
  bd: { countryCode: 'bd', countryName: 'Bangladesh',      currencyCode: 'BDT', symbol: '৳ ',    importPricePerKwh: 12,    exportPricePerKwh: 7,     dayPricePerKwh: 12,    nightPricePerKwh: 8,     annualKwh: 1100,  grant: 0,    grantSchemeName: 'SREDA Net Metering',            typicalTiltDeg: 23, touTariffExamples: GENERIC_TOU },
  lk: { countryCode: 'lk', countryName: 'Sri Lanka',       currencyCode: 'LKR', symbol: 'Rs ',   importPricePerKwh: 35,    exportPricePerKwh: 22,    dayPricePerKwh: 35,    nightPricePerKwh: 22,    annualKwh: 1200,  grant: 0,    grantSchemeName: 'SLSEA Net Plus',                typicalTiltDeg: 10, touTariffExamples: GENERIC_TOU },
  np: { countryCode: 'np', countryName: 'Nepal',           currencyCode: 'NPR', symbol: 'रु ',  importPricePerKwh: 12,    exportPricePerKwh: 7,     dayPricePerKwh: 12,    nightPricePerKwh: 8,     annualKwh: 800,   grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 28, touTariffExamples: GENERIC_TOU },
  bt: { countryCode: 'bt', countryName: 'Bhutan',          currencyCode: 'BTN', symbol: 'Nu ',   importPricePerKwh: 3.00,  exportPricePerKwh: 1.50,  dayPricePerKwh: 3.00,  nightPricePerKwh: 2.00,  annualKwh: 2000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 28, touTariffExamples: GENERIC_TOU },
  mv: { countryCode: 'mv', countryName: 'Maldives',        currencyCode: 'MVR', symbol: 'Rf ',   importPricePerKwh: 4.00,  exportPricePerKwh: 2.20,  dayPricePerKwh: 4.00,  nightPricePerKwh: 2.80,  annualKwh: 2500,  grant: 0,    grantSchemeName: 'STELCO PV Programme',           typicalTiltDeg: 5,  touTariffExamples: GENERIC_TOU },
  af: { countryCode: 'af', countryName: 'Afghanistan',     currencyCode: 'AFN', symbol: '؋ ',    importPricePerKwh: 6.00,  exportPricePerKwh: 3.00,  dayPricePerKwh: 6.00,  nightPricePerKwh: 4.00,  annualKwh: 600,   grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 33, touTariffExamples: GENERIC_TOU },

  // ── Central Asia ──────────────────────────────────────────────────
  kz: { countryCode: 'kz', countryName: 'Kazakhstan',      currencyCode: 'KZT', symbol: '₸ ',    importPricePerKwh: 21,    exportPricePerKwh: 12,    dayPricePerKwh: 21,    nightPricePerKwh: 14,    annualKwh: 3500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 40, touTariffExamples: GENERIC_TOU },
  uz: { countryCode: 'uz', countryName: 'Uzbekistan',      currencyCode: 'UZS', symbol: "so'm ", importPricePerKwh: 450,   exportPricePerKwh: 250,   dayPricePerKwh: 450,   nightPricePerKwh: 300,   annualKwh: 2500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },
  kg: { countryCode: 'kg', countryName: 'Kyrgyzstan',      currencyCode: 'KGS', symbol: 'с ',    importPricePerKwh: 0.77,  exportPricePerKwh: 0.40,  dayPricePerKwh: 0.77,  nightPricePerKwh: 0.50,  annualKwh: 2000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 40, touTariffExamples: GENERIC_TOU },
  tj: { countryCode: 'tj', countryName: 'Tajikistan',      currencyCode: 'TJS', symbol: 'SM ',   importPricePerKwh: 0.30,  exportPricePerKwh: 0.15,  dayPricePerKwh: 0.30,  nightPricePerKwh: 0.20,  annualKwh: 1800,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 38, touTariffExamples: GENERIC_TOU },
  tm: { countryCode: 'tm', countryName: 'Turkmenistan',    currencyCode: 'TMT', symbol: 'm ',    importPricePerKwh: 0.25,  exportPricePerKwh: 0.13,  dayPricePerKwh: 0.25,  nightPricePerKwh: 0.16,  annualKwh: 3000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 35, touTariffExamples: GENERIC_TOU },
  mn: { countryCode: 'mn', countryName: 'Mongolia',        currencyCode: 'MNT', symbol: '₮ ',    importPricePerKwh: 220,   exportPricePerKwh: 110,   dayPricePerKwh: 220,   nightPricePerKwh: 140,   annualKwh: 2200,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 45, touTariffExamples: GENERIC_TOU },

  // ── Middle East ───────────────────────────────────────────────────
  ae: { countryCode: 'ae', countryName: 'United Arab Emirates', currencyCode: 'AED', symbol: 'د.إ ', importPricePerKwh: 0.40, exportPricePerKwh: 0.27, dayPricePerKwh: 0.40, nightPricePerKwh: 0.32, annualKwh: 12000, grant: 0, grantSchemeName: 'Shams Dubai',                   typicalTiltDeg: 22, touTariffExamples: 'Slab tariff' },
  sa: { countryCode: 'sa', countryName: 'Saudi Arabia',    currencyCode: 'SAR', symbol: 'ر.س ',  importPricePerKwh: 0.30,  exportPricePerKwh: 0.18,  dayPricePerKwh: 0.30,  nightPricePerKwh: 0.20,  annualKwh: 13000, grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 22, touTariffExamples: GENERIC_TOU },
  qa: { countryCode: 'qa', countryName: 'Qatar',           currencyCode: 'QAR', symbol: 'ر.ق ',  importPricePerKwh: 0.18,  exportPricePerKwh: 0.10,  dayPricePerKwh: 0.18,  nightPricePerKwh: 0.12,  annualKwh: 14000, grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 22, touTariffExamples: GENERIC_TOU },
  kw: { countryCode: 'kw', countryName: 'Kuwait',          currencyCode: 'KWD', symbol: 'د.ك ',  importPricePerKwh: 0.030, exportPricePerKwh: 0.020, dayPricePerKwh: 0.030, nightPricePerKwh: 0.022, annualKwh: 15000, grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 25, touTariffExamples: GENERIC_TOU },
  bh: { countryCode: 'bh', countryName: 'Bahrain',         currencyCode: 'BHD', symbol: 'د.ب ',  importPricePerKwh: 0.030, exportPricePerKwh: 0.020, dayPricePerKwh: 0.030, nightPricePerKwh: 0.022, annualKwh: 11000, grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 22, touTariffExamples: GENERIC_TOU },
  om: { countryCode: 'om', countryName: 'Oman',            currencyCode: 'OMR', symbol: 'ر.ع ',  importPricePerKwh: 0.030, exportPricePerKwh: 0.020, dayPricePerKwh: 0.030, nightPricePerKwh: 0.022, annualKwh: 12000, grant: 0,    grantSchemeName: 'Sahim Net Metering',            typicalTiltDeg: 22, touTariffExamples: GENERIC_TOU },
  jo: { countryCode: 'jo', countryName: 'Jordan',          currencyCode: 'JOD', symbol: 'د.ا ',  importPricePerKwh: 0.20,  exportPricePerKwh: 0.10,  dayPricePerKwh: 0.20,  nightPricePerKwh: 0.13,  annualKwh: 3500,  grant: 0,    grantSchemeName: 'EMRC Net Metering',             typicalTiltDeg: 30, touTariffExamples: GENERIC_TOU },
  lb: { countryCode: 'lb', countryName: 'Lebanon',         currencyCode: 'LBP', symbol: 'ل.ل ',  importPricePerKwh: 6000,  exportPricePerKwh: 3000,  dayPricePerKwh: 6000,  nightPricePerKwh: 4000,  annualKwh: 3000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 33, touTariffExamples: GENERIC_TOU },
  il: { countryCode: 'il', countryName: 'Israel',          currencyCode: 'ILS', symbol: '₪ ',    importPricePerKwh: 0.60,  exportPricePerKwh: 0.21,  dayPricePerKwh: 0.60,  nightPricePerKwh: 0.45,  annualKwh: 5500,  grant: 0,    grantSchemeName: 'Net metering (PUA)',            typicalTiltDeg: 30, touTariffExamples: 'TOU residential' },
  ir: { countryCode: 'ir', countryName: 'Iran',            currencyCode: 'IRR', symbol: '﷼ ',    importPricePerKwh: 1500,  exportPricePerKwh: 800,   dayPricePerKwh: 1500,  nightPricePerKwh: 900,   annualKwh: 3000,  grant: 0,    grantSchemeName: 'SATBA FIT',                     typicalTiltDeg: 30, touTariffExamples: GENERIC_TOU },
  iq: { countryCode: 'iq', countryName: 'Iraq',            currencyCode: 'IQD', symbol: 'ع.د ',  importPricePerKwh: 70,    exportPricePerKwh: 40,    dayPricePerKwh: 70,    nightPricePerKwh: 45,    annualKwh: 4000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 30, touTariffExamples: GENERIC_TOU },
  ye: { countryCode: 'ye', countryName: 'Yemen',           currencyCode: 'YER', symbol: '﷼ ',    importPricePerKwh: 60,    exportPricePerKwh: 30,    dayPricePerKwh: 60,    nightPricePerKwh: 40,    annualKwh: 1500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 18, touTariffExamples: GENERIC_TOU },
  ps: { countryCode: 'ps', countryName: 'Palestine',       currencyCode: 'ILS', symbol: '₪ ',    importPricePerKwh: 0.55,  exportPricePerKwh: 0.20,  dayPricePerKwh: 0.55,  nightPricePerKwh: 0.40,  annualKwh: 3500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 30, touTariffExamples: GENERIC_TOU },
  sy: { countryCode: 'sy', countryName: 'Syria',           currencyCode: 'SYP', symbol: '£ ',    importPricePerKwh: 250,   exportPricePerKwh: 125,   dayPricePerKwh: 250,   nightPricePerKwh: 160,   annualKwh: 2500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 32, touTariffExamples: GENERIC_TOU },

  // ── Africa: North ─────────────────────────────────────────────────
  eg: { countryCode: 'eg', countryName: 'Egypt',           currencyCode: 'EGP', symbol: 'E£ ',   importPricePerKwh: 1.50,  exportPricePerKwh: 0.80,  dayPricePerKwh: 1.50,  nightPricePerKwh: 1.00,  annualKwh: 3000,  grant: 0,    grantSchemeName: 'EgyptERA Net Metering',         typicalTiltDeg: 28, touTariffExamples: GENERIC_TOU },
  ma: { countryCode: 'ma', countryName: 'Morocco',         currencyCode: 'MAD', symbol: 'د.م ',  importPricePerKwh: 1.20,  exportPricePerKwh: 0.60,  dayPricePerKwh: 1.20,  nightPricePerKwh: 0.80,  annualKwh: 2200,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 30, touTariffExamples: GENERIC_TOU },
  tn: { countryCode: 'tn', countryName: 'Tunisia',         currencyCode: 'TND', symbol: 'د.ت ',  importPricePerKwh: 0.36,  exportPricePerKwh: 0.18,  dayPricePerKwh: 0.36,  nightPricePerKwh: 0.22,  annualKwh: 2000,  grant: 0,    grantSchemeName: 'PROSOL ELEC',                   typicalTiltDeg: 30, touTariffExamples: GENERIC_TOU },
  dz: { countryCode: 'dz', countryName: 'Algeria',         currencyCode: 'DZD', symbol: 'د.ج ',  importPricePerKwh: 5.00,  exportPricePerKwh: 2.50,  dayPricePerKwh: 5.00,  nightPricePerKwh: 3.00,  annualKwh: 2500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 28, touTariffExamples: GENERIC_TOU },
  ly: { countryCode: 'ly', countryName: 'Libya',           currencyCode: 'LYD', symbol: 'ل.د ',  importPricePerKwh: 0.13,  exportPricePerKwh: 0.07,  dayPricePerKwh: 0.13,  nightPricePerKwh: 0.08,  annualKwh: 4500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 28, touTariffExamples: GENERIC_TOU },
  sd: { countryCode: 'sd', countryName: 'Sudan',           currencyCode: 'SDG', symbol: 'ج.س ',  importPricePerKwh: 8.00,  exportPricePerKwh: 4.00,  dayPricePerKwh: 8.00,  nightPricePerKwh: 5.00,  annualKwh: 1500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 18, touTariffExamples: GENERIC_TOU },

  // ── Africa: Sub-Saharan ───────────────────────────────────────────
  za: { countryCode: 'za', countryName: 'South Africa',    currencyCode: 'ZAR', symbol: 'R ',    importPricePerKwh: 3.20,  exportPricePerKwh: 0.85,  dayPricePerKwh: 3.20,  nightPricePerKwh: 1.80,  annualKwh: 4000,  grant: 0,    grantSchemeName: 'SARS Section 12B / IRR',        typicalTiltDeg: 30, touTariffExamples: 'Homeflex, Homepower' },
  ng: { countryCode: 'ng', countryName: 'Nigeria',         currencyCode: 'NGN', symbol: '₦ ',    importPricePerKwh: 70,    exportPricePerKwh: 40,    dayPricePerKwh: 70,    nightPricePerKwh: 50,    annualKwh: 1100,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 12, touTariffExamples: 'Band A/B/C/D/E' },
  ke: { countryCode: 'ke', countryName: 'Kenya',           currencyCode: 'KES', symbol: 'KSh ',  importPricePerKwh: 24,    exportPricePerKwh: 12,    dayPricePerKwh: 24,    nightPricePerKwh: 16,    annualKwh: 1200,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 5,  touTariffExamples: 'Domestic Lifeline' },
  et: { countryCode: 'et', countryName: 'Ethiopia',        currencyCode: 'ETB', symbol: 'Br ',   importPricePerKwh: 1.80,  exportPricePerKwh: 0.90,  dayPricePerKwh: 1.80,  nightPricePerKwh: 1.20,  annualKwh: 800,   grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 12, touTariffExamples: GENERIC_TOU },
  gh: { countryCode: 'gh', countryName: 'Ghana',           currencyCode: 'GHS', symbol: 'GH₵ ',  importPricePerKwh: 1.30,  exportPricePerKwh: 0.65,  dayPricePerKwh: 1.30,  nightPricePerKwh: 0.85,  annualKwh: 1500,  grant: 0,    grantSchemeName: 'Renewable Energy Act',          typicalTiltDeg: 8,  touTariffExamples: GENERIC_TOU },
  ci: { countryCode: 'ci', countryName: "Côte d'Ivoire",   currencyCode: 'XOF', symbol: 'CFA ',  importPricePerKwh: 100,   exportPricePerKwh: 55,    dayPricePerKwh: 100,   nightPricePerKwh: 65,    annualKwh: 1100,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 10, touTariffExamples: GENERIC_TOU },
  sn: { countryCode: 'sn', countryName: 'Senegal',         currencyCode: 'XOF', symbol: 'CFA ',  importPricePerKwh: 110,   exportPricePerKwh: 60,    dayPricePerKwh: 110,   nightPricePerKwh: 70,    annualKwh: 1100,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 15, touTariffExamples: GENERIC_TOU },
  tz: { countryCode: 'tz', countryName: 'Tanzania',        currencyCode: 'TZS', symbol: 'TSh ',  importPricePerKwh: 350,   exportPricePerKwh: 180,   dayPricePerKwh: 350,   nightPricePerKwh: 230,   annualKwh: 800,   grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 5,  touTariffExamples: GENERIC_TOU },
  ug: { countryCode: 'ug', countryName: 'Uganda',          currencyCode: 'UGX', symbol: 'USh ',  importPricePerKwh: 600,   exportPricePerKwh: 320,   dayPricePerKwh: 600,   nightPricePerKwh: 400,   annualKwh: 700,   grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 5,  touTariffExamples: GENERIC_TOU },
  zm: { countryCode: 'zm', countryName: 'Zambia',          currencyCode: 'ZMW', symbol: 'K ',    importPricePerKwh: 1.20,  exportPricePerKwh: 0.60,  dayPricePerKwh: 1.20,  nightPricePerKwh: 0.80,  annualKwh: 2000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 15, touTariffExamples: GENERIC_TOU },
  zw: { countryCode: 'zw', countryName: 'Zimbabwe',        currencyCode: 'USD', symbol: '$',     importPricePerKwh: 0.13,  exportPricePerKwh: 0.07,  dayPricePerKwh: 0.13,  nightPricePerKwh: 0.09,  annualKwh: 2500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 20, touTariffExamples: GENERIC_TOU },
  na: { countryCode: 'na', countryName: 'Namibia',         currencyCode: 'NAD', symbol: 'N$ ',   importPricePerKwh: 3.00,  exportPricePerKwh: 1.50,  dayPricePerKwh: 3.00,  nightPricePerKwh: 1.95,  annualKwh: 3000,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 25, touTariffExamples: GENERIC_TOU },
  bw: { countryCode: 'bw', countryName: 'Botswana',        currencyCode: 'BWP', symbol: 'P ',    importPricePerKwh: 1.30,  exportPricePerKwh: 0.65,  dayPricePerKwh: 1.30,  nightPricePerKwh: 0.85,  annualKwh: 2500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 22, touTariffExamples: GENERIC_TOU },
  mu: { countryCode: 'mu', countryName: 'Mauritius',       currencyCode: 'MUR', symbol: 'Rs ',   importPricePerKwh: 6.00,  exportPricePerKwh: 3.50,  dayPricePerKwh: 6.00,  nightPricePerKwh: 4.00,  annualKwh: 2400,  grant: 0,    grantSchemeName: 'CEB MSDG',                      typicalTiltDeg: 18, touTariffExamples: GENERIC_TOU },
  ao: { countryCode: 'ao', countryName: 'Angola',          currencyCode: 'AOA', symbol: 'Kz ',   importPricePerKwh: 28,    exportPricePerKwh: 15,    dayPricePerKwh: 28,    nightPricePerKwh: 18,    annualKwh: 1100,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 12, touTariffExamples: GENERIC_TOU },
  mz: { countryCode: 'mz', countryName: 'Mozambique',      currencyCode: 'MZN', symbol: 'MT ',   importPricePerKwh: 6.00,  exportPricePerKwh: 3.00,  dayPricePerKwh: 6.00,  nightPricePerKwh: 3.90,  annualKwh: 800,   grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 18, touTariffExamples: GENERIC_TOU },
  rw: { countryCode: 'rw', countryName: 'Rwanda',          currencyCode: 'RWF', symbol: 'FRw ',  importPricePerKwh: 220,   exportPricePerKwh: 120,   dayPricePerKwh: 220,   nightPricePerKwh: 145,   annualKwh: 600,   grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 5,  touTariffExamples: GENERIC_TOU },
  cm: { countryCode: 'cm', countryName: 'Cameroon',        currencyCode: 'XAF', symbol: 'FCFA ', importPricePerKwh: 80,    exportPricePerKwh: 40,    dayPricePerKwh: 80,    nightPricePerKwh: 50,    annualKwh: 800,   grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 8,  touTariffExamples: GENERIC_TOU },
  cd: { countryCode: 'cd', countryName: 'DR Congo',        currencyCode: 'CDF', symbol: 'FC ',   importPricePerKwh: 200,   exportPricePerKwh: 100,   dayPricePerKwh: 200,   nightPricePerKwh: 130,   annualKwh: 500,   grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 5,  touTariffExamples: GENERIC_TOU },
  ml: { countryCode: 'ml', countryName: 'Mali',            currencyCode: 'XOF', symbol: 'CFA ',  importPricePerKwh: 110,   exportPricePerKwh: 55,    dayPricePerKwh: 110,   nightPricePerKwh: 70,    annualKwh: 700,   grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 18, touTariffExamples: GENERIC_TOU },
  bf: { countryCode: 'bf', countryName: 'Burkina Faso',    currencyCode: 'XOF', symbol: 'CFA ',  importPricePerKwh: 110,   exportPricePerKwh: 55,    dayPricePerKwh: 110,   nightPricePerKwh: 70,    annualKwh: 600,   grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 12, touTariffExamples: GENERIC_TOU },
  mg: { countryCode: 'mg', countryName: 'Madagascar',      currencyCode: 'MGA', symbol: 'Ar ',   importPricePerKwh: 700,   exportPricePerKwh: 350,   dayPricePerKwh: 700,   nightPricePerKwh: 450,   annualKwh: 600,   grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 18, touTariffExamples: GENERIC_TOU },
  mw: { countryCode: 'mw', countryName: 'Malawi',          currencyCode: 'MWK', symbol: 'MK ',   importPricePerKwh: 130,   exportPricePerKwh: 65,    dayPricePerKwh: 130,   nightPricePerKwh: 85,    annualKwh: 500,   grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 14, touTariffExamples: GENERIC_TOU },

  // ── Oceania ───────────────────────────────────────────────────────
  au: { countryCode: 'au', countryName: 'Australia',       currencyCode: 'AUD', symbol: 'A$ ',   importPricePerKwh: 0.32,  exportPricePerKwh: 0.05,  dayPricePerKwh: 0.32,  nightPricePerKwh: 0.20,  annualKwh: 6000,  grant: 0,    grantSchemeName: 'STC rebate / state schemes',    typicalTiltDeg: 25, touTariffExamples: 'Time-of-Use, Demand tariff' },
  nz: { countryCode: 'nz', countryName: 'New Zealand',     currencyCode: 'NZD', symbol: 'NZ$ ',  importPricePerKwh: 0.34,  exportPricePerKwh: 0.10,  dayPricePerKwh: 0.34,  nightPricePerKwh: 0.18,  annualKwh: 7000,  grant: 0,    grantSchemeName: 'Buy-back rate (varies)',        typicalTiltDeg: 35, touTariffExamples: 'Day/Night, peak/off-peak' },
  fj: { countryCode: 'fj', countryName: 'Fiji',            currencyCode: 'FJD', symbol: 'FJ$ ',  importPricePerKwh: 0.40,  exportPricePerKwh: 0.20,  dayPricePerKwh: 0.40,  nightPricePerKwh: 0.25,  annualKwh: 2500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 18, touTariffExamples: GENERIC_TOU },
  pg: { countryCode: 'pg', countryName: 'Papua New Guinea', currencyCode: 'PGK', symbol: 'K ',   importPricePerKwh: 1.20,  exportPricePerKwh: 0.60,  dayPricePerKwh: 1.20,  nightPricePerKwh: 0.80,  annualKwh: 1500,  grant: 0,    grantSchemeName: GENERIC_GRANT,                   typicalTiltDeg: 10, touTariffExamples: GENERIC_TOU },
};

const FALLBACK: CountryDefaults = {
  countryCode: '',
  countryName: 'Your country',
  currencyCode: 'USD',
  symbol: '$',
  importPricePerKwh: 0.25,
  exportPricePerKwh: 0.08,
  dayPricePerKwh: 0.25,
  nightPricePerKwh: 0.12,
  annualKwh: 4000,
  grant: 0,
  grantSchemeName: GENERIC_GRANT,
  typicalTiltDeg: 30,
  touTariffExamples: GENERIC_TOU,
};

export function getCountryDefaults(countryCode: string): CountryDefaults {
  const cc = (countryCode || '').toLowerCase();
  if (COUNTRY_DEFAULTS[cc]) return COUNTRY_DEFAULTS[cc];
  return { ...FALLBACK, countryCode: cc };
}

export function currencySymbol(countryCode: string): string {
  return getCountryDefaults(countryCode).symbol;
}

/** Sorted list of all supported countries — for the country-override dropdown. */
export function listSupportedCountries(): { code: string; name: string }[] {
  return Object.values(COUNTRY_DEFAULTS)
    .map((c) => ({ code: c.countryCode, name: c.countryName }))
    .sort((a, b) => a.name.localeCompare(b.name));
}
